# Disable PR triggers (default is it will be triggered whenever a PR is created)
pr: none
# Disable CI triggers entirely (this pipeline is used for testing and will be run manually)
trigger: none

pool:
  name: 'ubuntu-agent-pool' # Self-hosted

variables:
- group: ubuntu-agent-info

stages:

- stage: StartVM
  displayName: "Start self-hosted agent"
  jobs:
    - template: ../../Azure-Pipelines/jobs/start_agent.yml
      parameters:
        subscriptionId: $(subscriptionId)
        rgName: $(rgName)
        vmName: $(vmName)

- stage: Demo
  displayName: "Demo stage"
  jobs:
  - job: DemoJob
    displayName: "Demo job"
    steps:
      - script: echo "Hello, Azure-Pipelines!"
        displayName: "Print a message"

- stage: DeallocateVM
  displayName: "Deallocate self-hosted agent"
  jobs:
    - template: ../../Azure-Pipelines/jobs/stop_agent.yml
      parameters:
        subscriptionId: $(subscriptionId)
        rgName: $(rgName)
        vmName: $(vmName)
