parameters:
- name: azureSubscription
  type: string
  default: 'AzureSubscriptionServiceConnection'
- name: subscriptionId
  type: string
  default: ''
- name: rgName
  type: string
  default: ''
- name: vmName
  type: string
  default: ''
- name: apiVersion
  type: string
  default: '2024-07-01'

jobs:
  - job: StartVM
    displayName: "Start self-hosted agent"
    pool: server
    steps:

      - task: InvokeRESTAPI@1
        displayName: "Start VM using REST API"
        inputs:
          connectionType: 'connectedServiceNameARM'
          azureServiceConnection: ${{ parameters.azureSubscription }}
          method: 'POST'
          urlSuffix: /subscriptions/${{ parameters.subscriptionId }}/resourceGroups/${{ parameters.rgName }}/providers/Microsoft.Compute/virtualMachines/${{ parameters.vmName }}/start?api-version=${{ parameters.apiVersion }}
          waitForCompletion: 'false'

      - task: Delay@1
        displayName: "Wait for VM to start"
        inputs:
          delayForMinutes: '1'

      - task: InvokeRESTAPI@1
        displayName: "Check VM is running"
        inputs:
          connectionType: 'connectedServiceNameARM'
          azureServiceConnection: ${{ parameters.azureSubscription }}
          method: 'GET'
          urlSuffix: /subscriptions/${{ parameters.subscriptionId }}/resourceGroups/${{ parameters.rgName }}/providers/Microsoft.Compute/virtualMachines/${{ parameters.vmName }}?$expand=InstanceView&api-version=${{ parameters.apiVersion }}
          waitForCompletion: 'false'
          successCriteria: eq(root['properties']['instanceView']['statuses'][1]['code'], 'PowerState/running')