parameters:
  - name: pythonVersion
    type: string
    default: '3.x'

jobs:
  - job: Test
    displayName: 'Run tests'
    steps:
      
      - task: UsePythonVersion@0
        displayName: 'Set Python version to ${{ parameters.pythonVersion }}'
        inputs:
          versionSpec: '${{ parameters.pythonVersion }}'
        enabled: false # Disable, as Python is already installed on the agent

      - script: |
          sudo apt install python3.12-venv
          python3 -m venv myenv
          source myenv/bin/activate
          pip install pytest
          pytest
        displayName: 'Run pytest tests'