parameters:
- name: environmentName
  type: string


jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment:
    name: {{ parameters.environmentName }}
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment