trigger:
  branches:
    include:
    - develop
    - main
    exclude:
    - feature/*

pool:
  name: ubuntu-agent-pool

stages:
  - template: ../../Azure DevOps/stages/function_app_build.yml
    parameters:
      appName: 'func-azuredevops-test'
    # Other parameters could be passed here, but the default values are what is needed already

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }}
    - template: ../../Azure DevOps/stages/function_app_deploy.yml      
      # Pass parameters here
  
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }}
    - template: ../../Azure DevOps/stages/function_app_deploy.yml
      # Pass parameters here


