trigger:
  branches:
    include:
    - develop
    - main
    exclude:
    - feature/*

pool:
  name: ubuntu-agent-pool

stages:
  - stage: Build
    displayName: Build Function App
    jobs:
    - template: ../../Azure DevOps/stages/function_app_build.yml
      parameters:
        appName: 'func-azuredevops-test'
      # Other parameters could be passed here, but the default values are what is needed already

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }}
    - stage: Deploy_Dev
      displayName: Deploy Function App to development environment # in this example in the sandbox, there is no difference as only one RG and one App have been created
      # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      jobs:
      - template: ../../Azure DevOps/stages/function_app_deploy.yml
        # Pass parameters here
  
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }}
    - stage: Deploy_Prod
      displayName: Deploy Function App to production environment # in this example in the sandbox, there is no difference as only one RG and one App have been created
      jobs:
      - template: ../../Azure DevOps/stages/function_app_deploy.yml
        # Pass parameters here


