trigger:
  branches:
    include:
    - develop
    - main

pool:
  name: ubuntu-agent-pool

stages:

  - stage: BuildAndDeployDev
    displayName: Build and deploy Function App to development environment
    jobs:
      - template: ../../Azure DevOps/stages/function_app_build.yml
        parameters:
          appName: 'func-azuredevops-test'
    # Other parameters could be passed here, but the default values are what is needed already

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }} :
    - template: ../../Azure DevOps/stages/function_app_deploy.yml      
      # Pass parameters here
  
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }} :
    - template: ../../Azure DevOps/stages/function_app_deploy.yml
      # Pass parameters here


