trigger:
  branches:
    include:
    - develop
    - main

pool:
  name: ubuntu-agent-pool

stages:

  - stage: Build
    displayName: Build Function App
    jobs:
      - template: ../../Azure DevOps/stages/function_app_build.yml
      # Pass parameters here

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }} :
    - template: ../../Azure DevOps/stages/function_app_deploy.yml      
      parameters:
        appName: func-azdotest-dev-001
  
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/head/develop') }} :
    - template: ../../Azure DevOps/stages/function_app_deploy.yml
      parameters:
        appName: func-azdotest-prod-001


