trigger:
  branches:
    include:
    - develop
    - main
    exclude:
    - feature/*

pool:
  name: ubuntu-agent-pool

parameters:
- name: appName
  type: string
  default: 'func-azuredevops-test'
- name: pythonVersion
  type: string
  default: '3.x'

stages:
- stage: build
  displayName: Build Function App

  jobs:
  - job: build
    displayName: azfunction_${{ parameters.appName }}_build
    steps:
      - checkout: none

      - task: SelectiveCheckout@0
        inputs:
          pathsToCheckout: "/Function Apps/func-azuredevops-test"

      - task: UsePythonVersion@0
        displayName: "Set Python version to ${{ parameters.pythonVersion }}"
        inputs:
          versionSpec: '${{ parameters.pythonVersion }}'
        enabled: false # disable this task as the agent already has python installed
        
      - bash: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
        displayName: "Install pip using package manager"

      - bash: |
          echo "Working directory: $(pwd)"
          echo "Contents of current directory:"
          ls -l
          echo "Contents of parent directory:"
          ls -l ../
        displayName: "Debug Repository Checkout"

      - bash: |
          if [ -f extensions.csproj ]
          then
              dotnet build extensions.csproj --output ./bin
          fi
          pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        displayName: "Install dependencies"
        # workingDirectory: "$(Build.SourcesDirectory)/Function Apps/func-azuredevops-test"

      - bash: |
          sudo apt-get update
          sudo apt-get install -y zip
        displayName: "Install zip utility"

      - task: ArchiveFiles@2
        displayName: "Archive files (zip function files)"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
          artifactName: 'function-app-artifact'
