trigger:
  branches:
    include:
    - develop
    - main

pool:
  name: ubuntu-agent-pool

stages:

  - stage: Build
    displayName: Build Function App
    jobs:
      - template: ../../Azure DevOps/stages/function_app_build.yml
      # Pass parameters here

  - stage: Deploy
    displayName: Deploy Function App
    jobs:
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
        - template: ../../Azure DevOps/stages/function_app_deploy.yml
          parameters:
            appName: func-azdotest-dev-001
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        - template: ../../Azure DevOps/stages/function_app_deploy.yml
          parameters:
            appName: func-azdotest-prod-001
      - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/develop') && ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        - job: Fallback
          displayName: Fallback job
          steps:
            - script: echo "No deployment needed for this run as it was not triggered by a PR to either 'develop' or 'main' branch."


