trigger:
  branches:
    include:
    - develop
    - main
    exclude:
    - feature/*

pool:
  name: ubuntu-agent-pool

parameters:
- name: appName
  type: string
  default: 'func-azuredevops-test'
- name: pythonVersion
  type: string
  default: '3.11'

stages:
- stage: build
  displayName: Build Function App

  jobs:
  - job: build
    displayName: azfunction_${{ parameters.appName }}_build
    steps:
      - script: |
          mkdir -p /azp/_work/_tool
          ln -s /azp/_work/_tool /opt/hostedtoolcache
        displayName: "Symlink Python Tools Directory to Agent Tools Directory"
        
      - task: UsePythonVersion@0
        displayName: "Set Python version to ${{ parameters.pythonVersion }}"
        inputs:
          versionSpec: '${{ parameters.pythonVersion }}'

      - bash: |
          if [ -f extensions.csproj ]
          then
              dotnet build extensions.csproj --output ./bin
          fi
          pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt

      - task: ArchiveFiles@2
        displayName: "Archive files (zip function files)"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
          artifactName: 'function-app-artifact'
