# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Disable PR triggers (default is it will be triggered whenever a PR is created)
pr: none

trigger:
  branches:
    include:
      - develop
      - main
  paths:
    include:
      - "Azure-Pipelines/demo-deploy-container-app/src/"

pool:
  name: ubuntu-agent-pool # Self-hosted

stages:
  - stage: Build
    displayName: "Build and Push"
    jobs:
      - template: ../../../Azure-Pipelines/jobs/function_app_container_build.yml
        parameters:
          dockerRegistryServiceConnection: f176961d-a0bc-42b6-a0b9-7917952cc5fd
          imageRepository: azurefunctionsimage
          DockerfilePath: '$(Build.SourcesDirectory)/Azure-Pipelines/demo-deploy-container-app/src/Dockerfile'
          tag: '$(Build.BuildId)'

  - stage: Deploy
    displayName: "Deploy"
    jobs:
      - template: ../../../Azure-Pipelines/jobs/function_app_container_deploy.yml
        parameters:
          azureSubscription: AzureSubscriptionServiceConnection
          appName: func-container-demo-003
          # appSettings: '-DOCKER_REGISTRY_SERVER_URL $(registry_url) -DOCKER_REGISTRY_SERVER_USERNAME $(registry_username) -DOCKER_REGISTRY_SERVER_PASSWORD $(registry_password)'
          containerRegistry: acrdemo003.azurecr.io
          imageRepository: azurefunctionsimage
          tag: '$(Build.BuildId)'