# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Disable PR triggers (default is it will be triggered whenever a PR is created)
pr: none

trigger:
  branches:
    include:
      - develop
      - main
  paths:
    include:
      - "Azure-Pipelines/demo-deploy-container-app/src/"

pool:
  name: ubuntu-agent-pool # Self-hosted

stages:
  - stage: Build
    displayName: "Build and Push"
    jobs:
      - template: ../../../Azure-Pipelines/jobs/function_app_container_build.yml
        parameters:
          dockerRegistryServiceConnection: 7e56544d-d730-49bf-8158-24efd406a5b6
          imageRepository: azurefunctionsimage
          DockerfilePath: '$(Build.SourcesDirectory)/Azure-Pipelines/demo-deploy-container-app/src/Dockerfile'
          tag: '$(Build.BuildId)'

  - stage: Deploy
    displayName: "Deploy"
    jobs:
      - template: ../../../Azure-Pipelines/jobs/function_app_container_deploy.yml
        parameters:
          azureSubscription: 'AzureSubscriptionServiceConnection'
          appName: func-container-demo-003
          containerRegistry: acrdemo003.azurecr.io
          imageRepository: azurefunctionsimage
          tag: '$(Build.BuildId)'
