pool:
  name: 'ubuntu-agent-pool' # Self-hosted

stages:

- stage: StartVM
  displayName: "Start self-hosted agent"
  jobs:
    - template: ../../Azure DevOps/jobs/start_agent.yml

- stage: Demo
  displayName: "Demo stage"
  jobs:
  - job: DemoJob
    displayName: "Demo job"
    steps:
      - script: echo "Hello, Azure DevOps!"
        displayName: "Print a message"

- stage: DeallocateVM
  displayName: "Deallocate self-hosted agent"
  jobs:
    - template: ../../Azure DevOps/jobs/stop_agent.yml
