pool:
  name: 'ubuntu-agent-pool'

stages:
- stage: Demo
  displayName: "Demo stage"
  jobs:
  - job: DemoJob
    displayName: "Demo job"
    steps:
      - script: echo "Hello, Azure DevOps!"
        displayName: "Print a message"
