# Disable PR triggers (default is it will be triggered whenever a PR is created)
pr: none

trigger:
  branches:
    include:
    - develop
    - main
  paths:
    include:
    - "Azure DevOps/demo-start-stop/*"

pool:
  name: 'ubuntu-sh-agent-pool' # Self-hosted

variables:
- group: ubuntu-sh-agent-info

stages:

  - stage: StartVM
    displayName: "Start self-hosted agent"
    jobs:
      - template: ../../Azure DevOps/jobs/start_agent.yml
        parameters:
          subscriptionId: $(subscriptionId)
          rgName: $(rgName)
          vmName: $(vmName)

  - stage: Build
    displayName: "Build Python app"
    dependsOn: StartVM
    jobs:
      - template: ../../Azure DevOps/jobs/python_app_build.yml

    - stage: Validate
    displayName: "Test Python app"
    dependsOn: Build
    jobs:
      - template: ../../Azure DevOps/jobs/python_app_test.yml

  - stage: Deploy
    displayName: "Deploy Python app"
    dependsOn: Build
    jobs:
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
        - template: ../../Azure DevOps/jobs/function_app_deploy.yml
          parameters:
            appName: func-azdotest-dev-001
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        - template: ../../Azure DevOps/jobs/function_app_deploy.yml
          parameters:
            appName: func-azdotest-prod-001
      - ${{ if not(or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))) }}:
        - job: Fallback
          displayName: "Fallback job"
          steps:
            - script: echo "No deployment for this run as it was not triggered by a PR to either 'develop' or 'main' branch."