parameters:
- name: dockerRegistryServiceConnection
  type: string
- name: imageRepository
  type: string
  default: 'azurefunctionsimage'
- name: DockerfilePath
  type: string
- name: tag
  type: string
  default: '$(Build.BuildId)'

jobs:
  - job: Build
    displayName: "Build and Push containerized Function App"
    steps:
      - task: Docker@2
        displayName: "Build and Push an image"
        inputs:
          command: buildAndPush
          containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
          repository: ${{ parameters.imageRepository }}
          Dockerfile: ${{ parameters.DockerfilePath }}
          tags: |
            ${{ parameters.tag }}
