parameters:
  - name: pythonVersion
    type: string
    default: '3.x'
  - name: projectDirectory
    type: string

jobs:
  - job: Test
    displayName: 'Run tests'
    steps:
      
      - task: UsePythonVersion@0
        displayName: 'Set Python version to ${{ parameters.pythonVersion }}'
        inputs:
          versionSpec: '${{ parameters.pythonVersion }}'
        enabled: false # Disable, as Python is already installed on the agent

      - script: |
          sudo apt-get install -y python3-venv
          cd ${{ parameters.projectDirectory }}
          pwd
          python3 -m venv myenv
          source myenv/bin/activate
          pip install -r requirements.txt
          pip install pytest
          pytest
          exit_code=$?
          deactivate
          rm -rf myenv
          if [ $exit_code -ne 0 ]; then
            echo "Tests failed."
            exit $exit_code
          fi
        displayName: 'Run pytest tests'